global:
  ingress:
    httpNodePort: 30080
    httpsNodePort: 32438

website:
  image:
    name: tributech-ui-oauth-sample
    tag: local
    pullPolicy: Never

  service:
    port: 4200
    type: ClusterIP

  ingress:
    host: website.local

# =========================
# POSTGRESQL CONFIG
# =========================
postgresql:
  enabled: true
  auth:
    username: keycloak
    password: B2qazwe1
    database: keycloakdb

  primary:
    service:
      type: ClusterIP
    persistence:
      enabled: false

# =========================
# PGADMIN CONFIG
# =========================
pgadmin4:
  enabled: true

  image:
    repository: dpage/pgadmin4
    tag: "latest"
    pullPolicy: IfNotPresent

  extraArgs:
    - "--load-servers"

  env:
    email: admin@tributech.io
    password: B2qazwe1

  service:
    type: ClusterIP
    port: 8090

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: pgadmin.local
        paths:
          - path: /
            pathType: Prefix

  serverDefinitions:
    enabled: true
    servers:
      "1":
        Name: tributech-postgres
        Group: "Server Group Automatic"
        Host: "tributech-app-postgresql.default.svc.cluster.local"
        Port: 5432
        MaintenanceDB: keycloakdb
        Username: keycloak
        SSLMode: prefer