global:
  ingress:
    httpNodePort: 30080
    httpsNodePort: 32438

# =========================
# INGRESS CONTROLLER CONFIG
# =========================
#ingress-nginx:
#  controller:
#    service:
#      type: NodePort
#      nodePorts:
#        http: 30080
#        https: 32438
#    ingressClassResource:
#      name: nginx
#    ingressClass: nginx
#    publishService:
#      enabled: false
#    allowSnippetAnnotations: true  # essential for setting server-snippet in ingress
#    admissionWebhooks:
#      annotations:
#        nginx.ingress.kubernetes.io/annotations-risk-level: "Critical"    
#    config:
#      enable-access-log: "true"
#      log-level: debug
# =========================
# WEBSITE CONFIG
# =========================
website:
  image:
    name: tributech-ui-oauth-sample
    tag: local
    pullPolicy: Never

  service:
    port: 4200
    type: ClusterIP

  ingress:
    host: website.local

# =========================
# POSTGRESQL CONFIG
# =========================
postgresql:
  enabled: true
  auth:
    username: keycloak
    password: B2qazwe1
    database: keycloakdb

  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: 32001
    persistence:
      enabled: false

# =========================
# PGADMIN CONFIG
# =========================
pgadmin4:
  enabled: true

  image:
    repository: dpage/pgadmin4
    tag: "latest"
    pullPolicy: IfNotPresent

  extraArgs:
    - "--load-servers" # troubleshoot why the server is not visible

  env:
    email: admin@tributech.io
    password: B2qazwe1

  service:
    type: ClusterIP
    port: 8090

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: pgadmin.local
        paths:
          - path: /
            pathType: Prefix

  serverDefinitions:
    enabled: true
    servers:
      "1":
        Name: tributech-postgres
        Group: "Server Group 1"
        Host: "postgresql.local" # postgresql.local cannot be resovled for some reasons
        HostAddr: "164.90.234.114"
        Port: 32001
        MaintenanceDB: keycloakdb
        Username: keycloak
        SSLMode: prefer

# =========================
# KEYCLOAK CONFIG
# =========================
#keycloak:
#  enabled: true
#
#  headless:
#    enabled: false
#
#  tls:
#    enabled: false
#
#  auth:
#    adminUser: admin
#    adminPassword: B2qazwe1
#
#  postgresql:
#    enabled: false
#
#  externalDatabase:
#    host: tributech-app-postgresql
#    user: keycloak
#    password: B2qazwe1
#    database: keycloakdb
#
#  service:
#    type: ClusterIP
#    ports:
#      http: 8080
#    http:
#      enabled: true
#
#  ingress:
#    enabled: true
#    ingressClassName: nginx
#    hostname: keycloak.local
#    tls: true
#    path: /
#    extraTls:
#      - hosts:
#          - keycloak.local
#        secretName: keycloak-local-tls
#    extraPaths:
#      - path: /realms/
#        pathType: Prefix
#        backend:
#          service:
#            name: tributech-app-keycloak
#            port:
#              name: http    
#      - path: /resources/
#        pathType: Prefix
#        backend:
#          service:
#            name: tributech-app-keycloak
#            port:
#              name: http
#    annotations:
#      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#      nginx.ingress.kubernetes.io/ssl-redirect: "true"
#      nginx.ingress.kubernetes.io/use-regex: "true"
#      nginx.ingress.kubernetes.io/cors-allow-origin: "http://keycloak.local:30080, http://keycloak.local, http://keycloak.local:30080, http://website.local"
#      nginx.ingress.kubernetes.io/configuration-snippet: |
#        proxy_set_header Host $host;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto $scheme;
#        proxy_set_header X-Forwarded-Host $host;
#        proxy_set_header X-Forwarded-Port 32438;
#        proxy_set_header Forwarded "proto=https;host=$host;port=32438";
#
#  extraEnvVars:
#    - name: KC_PROXY_HEADERS
#      value: "xforwarded"
##    - name: KC_HTTP_ENABLED
##      value: "true"
#    - name: KC_PROXY
#      value: "edge"
##    - name: KC_HOSTNAME
##      value: "keycloak.local"    
##    - name: KC_HOSTNAME_PORT
##      value: "30080"
##    - name: KC_HOSTNAME_URL
##      value: "http://keycloak.local:32438"
##    - name: KC_HOSTNAME_ADMIN_URL
##      value: "http://keycloak.local:32438"
##
#  keycloakConfigCli:
#    enabled: true    
#    existingConfigmap: tributech-keycloak-realm-config
#    extraEnvVars:
#      - name: KEYCLOAK_URL
#        value: "http://tributech-app-keycloak.default.svc.cluster.local:8080"
#      - name: KEYCLOAK_USER
#        value: "admin"
#      - name: KEYCLOAK_PASSWORD
#        value: "B2qazwe1"
#
#