apiVersion: v1
kind: ConfigMap
metadata:
  name: tributech-keycloak-realm-config
data:
  node-realm.yaml: |
    realm: node
    enabled: true
    clients:
      - clientId: dataspace-admin
        publicClient: true
        standardFlowEnabled: true
        redirectUris:
          - "https://website.local:{{ .Values.global.ingress.httpsNodePort }}//*"
        webOrigins:
          - "https://website.local:{{ .Values.global.ingress.httpsNodePort }}/"
    users:
      - username: angular-user
        enabled: true
        emailVerified: true
        credentials:
          - type: password
            value: B2qazwe1
            temporary: false