apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-config-cli
  labels:
    app: keycloak-config-cli
spec:
  backoffLimit:
  template:
    metadata:
      labels:
        app: keycloak-config-cli
    spec:
      restartPolicy: Never
      containers:
        - name: keycloak-config-cli
          image: adorsys/keycloak-config-cli:latest
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak.default.svc.cluster.local:8080/"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "B2qazwe1"
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: "120s"
            - name: KEYCLOAK_SSLVERIFY
              value: "false"
            - name: IMPORT_FILES_LOCATIONS
              value: "/config/node-realm.yaml"
          volumeMounts:
            - name: realm-config
              mountPath: /config
      volumes:
        - name: realm-config
          configMap:
            name: tributech-keycloak-realm-config