apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
#      volumes:
#        - name: realm-config
#          configMap:
#            name: tributech-keycloak-realm-config    
      containers:
        - name: keycloak
          image: keycloak/keycloak:26.2
          args:
            - "start"
            - "--proxy-headers"
            - "xforwarded"
            - "--http-enabled"
            - "true"
            - "--hostname-strict"
            - "false"
            - "--hostname"
            - "https://keycloak.local:{{ .Values.global.ingress.httpsNodePort }}"
          env:
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "B2qazwe1"
            - name: KC_HEALTH_ENABLED
              value: "false"
            - name: KC_METRICS_ENABLED
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "tributech-app-postgresql"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "keycloakdb"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              value: "B2qazwe1"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443

#        - name: keycloak-config-cli
#          image: adorsys/keycloak-config-cli:latest
#          env:
#            - name: KEYCLOAK_URL
#              value: "http://keycloak.default.svc.cluster.local:8080/"
#            - name: KEYCLOAK_USER
#              value: "admin"
#            - name: KEYCLOAK_PASSWORD
#              value: "B2qazwe1"
#            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
#              value: "true"              
#            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
#              value: "30s"          
#            - name: KEYCLOAK_SSLVERIFY
#              value: "false"                                
#            - name: IMPORT_FILES_LOCATIONS
#              value: "/config/node-realm.yaml"
#          volumeMounts:
#            - name: realm-config
#              mountPath: /config
#
#          command: ["/bin/sh", "-c"]
#          args:
#             - |
#               sleep 300 && YOUR_EXISTING_COMMAND

# until curl -s http://keycloak.default.svc.cluster.local:8080/realms/master > /dev/null; do              