apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          args:
            - "start"
            - "--proxy-headers"
            - "xforwarded"
            - "--http-enabled"
            - "true"
            - "--hostname-strict"
            - "false"
            - "--hostname"
            - "https://{{ .Values.keycloak.hostname }}:{{ .Values.global.ingress.httpsNodePort }}"
          env:
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.keycloak.admin.user }}"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "{{ .Values.keycloak.admin.password }}"
            - name: KC_HEALTH_ENABLED
              value: "false"
            - name: KC_METRICS_ENABLED
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_DB
              value: "{{ .Values.keycloak.db.vendor }}"
            - name: KC_DB_URL_HOST
              value: "{{ .Values.keycloak.db.host }}"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "{{ .Values.keycloak.db.name }}"
            - name: KC_DB_USERNAME
              value: "{{ .Values.keycloak.db.username }}"
            - name: KC_DB_PASSWORD
              value: "{{ .Values.keycloak.db.password }}"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443