apiVersion: v1
kind: Service
metadata:
  name: tributech-website-service
spec:
  selector:
    app: tributech-website
  ports:
  - port: {{ .Values.website.service.port }}
    targetPort: {{ .Values.website.service.port }}
  type: {{ .Values.website.service.type }}